
export const Users = [
  {
    id:1,
    profilePicture: "profile-pics/profile1.png",
    username: "Ajay",
  },
  {
    id:2,
    profilePicture: "profile-pics/profile2.png",
    username: "Zufi",
  },
  {
    id:3,
    profilePicture: "profile-pics/profile3.png",
    username: "Thanoj",
  },
  {
    id:4,
    profilePicture: "profile-pics/profile4.png",
    username: "Naga Chaithanya",
  },
  {
    id:5,
    profilePicture: "profile-pics/profile5.png",
    username: "Lokesh",
  },
  {
    id:6,
    profilePicture: "profile-pics/profile6.png",
    username: "Vivek Vardhan",
  },
  {
    id:7,
    profilePicture: "profile-pics/profile7.png",
    username: "Mounima",
  },
  {
    id:8,
    profilePicture: "profile-pics/profile8.png",
    username: "Riah",
  },
  {
    id:9,
    profilePicture: "profile-pics/profile9.png",
    username: "Uday",
  },
  {
    id:10,
    profilePicture: "profile-pics/profile10.png",
    username: "Safak",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "posts/post1.png",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "posts/post2.png",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "posts/post3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "posts/post4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "posts/post5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "posts/post6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "posts/post7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "posts/post8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "posts/post9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "posts/post10.png",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];